//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artikel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public int IdArtikel { get; set; }
        public string Judul { get; set; }
        public string IsiArtikel { get; set; }
        public string ThumbnailURL { get; set; }
    }
}
